function mimeForKey(key: string): string {
  const ext = key.toLowerCase().split(".").pop();
  if (ext === "jpg" || ext === "jpeg") return "image/jpeg";
  if (ext === "webp") return "image/webp";
  return "image/png";
}

// `no-cache` (not "don't cache" — HTTP naming is misleading) means "cache
// this, but always revalidate with the server before using it," paired
// with an ETag so a same-content revalidation is a cheap 304 with no image
// bytes re-sent. Plain max-age caching (what this used to be) blindly trusts
// a cached copy until it expires — harmless when a book's assets are only
// ever written once, but wrong once "regenerate entire book" (admin
// actions.ts) can overwrite the exact same URL/R2 key with new content:
// a customer or admin who already loaded the old image wouldn't see the
// new one until the old cache entry happened to expire.
function assetHeaders(object: R2ObjectBody, filename: string): Record<string, string> {
  return {
    "Content-Type": object.httpMetadata?.contentType || mimeForKey(filename),
    "Cache-Control": "private, no-cache",
    ETag: object.httpEtag,
  };
}

function notModified(request: Request, object: R2ObjectBody): boolean {
  const ifNoneMatch = request.headers.get("If-None-Match");
  return ifNoneMatch !== null && ifNoneMatch === object.httpEtag;
}

export async function handleGetAsset(bookId: string, filename: string, env: Env, request: Request): Promise<Response> {
  // Filenames are generated by our own code (character-sheet.png, cover-front.png,
  // page-01.png, ...) — reject anything else rather than trust the URL blindly.
  if (!/^[a-z0-9-]+\.png$/i.test(filename)) {
    return new Response("Not found", { status: 404 });
  }

  const object = await env.PHOTOS.get(`${bookId}/${filename}`);
  if (!object) return new Response("Not found", { status: 404 });

  const headers = assetHeaders(object, filename);
  if (notModified(request, object)) return new Response(null, { status: 304, headers });
  return new Response(object.body, { headers });
}

// Same validation as handleGetAsset, for the paid, high-quality assets
// stored under the book's `full/` R2 prefix (kept distinct from the free
// preview so the two qualities can never collide or be confused).
export async function handleGetFullAsset(bookId: string, filename: string, env: Env, request: Request): Promise<Response> {
  if (!/^[a-z0-9-]+\.png$/i.test(filename)) {
    return new Response("Not found", { status: 404 });
  }

  const object = await env.PHOTOS.get(`${bookId}/full/${filename}`);
  if (!object) return new Response("Not found", { status: 404 });

  const headers = assetHeaders(object, filename);
  if (notModified(request, object)) return new Response(null, { status: 304, headers });
  return new Response(object.body, { headers });
}
