function mimeForKey(key: string): string {
  const ext = key.toLowerCase().split(".").pop();
  if (ext === "jpg" || ext === "jpeg") return "image/jpeg";
  if (ext === "webp") return "image/webp";
  return "image/png";
}

export async function handleGetAsset(bookId: string, filename: string, env: Env): Promise<Response> {
  // Filenames are generated by our own code (character-sheet.png, cover-front.png,
  // page-01.png, ...) — reject anything else rather than trust the URL blindly.
  if (!/^[a-z0-9-]+\.png$/i.test(filename)) {
    return new Response("Not found", { status: 404 });
  }

  const object = await env.PHOTOS.get(`${bookId}/${filename}`);
  if (!object) return new Response("Not found", { status: 404 });

  return new Response(object.body, {
    headers: {
      "Content-Type": object.httpMetadata?.contentType || mimeForKey(filename),
      "Cache-Control": "private, max-age=3600",
    },
  });
}

// Same validation as handleGetAsset, for the paid, high-quality assets
// stored under the book's `full/` R2 prefix (kept distinct from the free
// preview so the two qualities can never collide or be confused).
export async function handleGetFullAsset(bookId: string, filename: string, env: Env): Promise<Response> {
  if (!/^[a-z0-9-]+\.png$/i.test(filename)) {
    return new Response("Not found", { status: 404 });
  }

  const object = await env.PHOTOS.get(`${bookId}/full/${filename}`);
  if (!object) return new Response("Not found", { status: 404 });

  return new Response(object.body, {
    headers: {
      "Content-Type": object.httpMetadata?.contentType || mimeForKey(filename),
      "Cache-Control": "private, max-age=3600",
    },
  });
}
