// Ambient augmentation (no imports/exports — must stay global scope) merging
// secret/var bindings into the `Env` interface generated by `wrangler types`
// into worker-configuration.d.ts. These come from `.dev.vars` locally and
// `wrangler secret put` in production, so they aren't declared in
// wrangler.jsonc and wrangler types can't see them.
interface Env {
  OPENAI_API_KEY: string;
  STRIPE_SECRET_KEY: string;
  STRIPE_WEBHOOK_SECRET: string;
}
