// Ambient augmentation (no imports/exports — must stay global scope) merging
// secret/var bindings into the `Env` interface generated by `wrangler types`
// into worker-configuration.d.ts. These come from `.dev.vars` locally and
// `wrangler secret put` in production, so they aren't declared in
// wrangler.jsonc and wrangler types can't see them.
interface Env {
  OPENAI_API_KEY: string;
  STRIPE_SECRET_KEY: string;
  STRIPE_WEBHOOK_SECRET: string;
  // Empty string until the user supplies real OAuth app credentials — the
  // corresponding provider's /start route returns a clear "not configured"
  // error rather than attempting a doomed redirect (see worker/routes/oauth.ts).
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  FACEBOOK_APP_ID: string;
  FACEBOOK_APP_SECRET: string;
  RESEND_API_KEY: string;
  PAYPAL_CLIENT_ID: string;
  PAYPAL_CLIENT_SECRET: string;
  // "https://api-m.sandbox.paypal.com" for local dev, "https://api-m.paypal.com"
  // in production — see worker/paypal.ts.
  PAYPAL_API_BASE: string;
}

// *.ttf module typing (for the "Data" rule in wrangler.jsonc) is
// auto-generated by `wrangler types` into worker-configuration.d.ts — no
// manual declaration needed here.
